Ib-naganocake/naganocake

config/application.rb, config/locales/devise.ja.yml, config/locales/ja.yml
=> Add ja_locales

app/controllers/admin/sessions_controller.rb, app/views/admin/sessions/new.html.erb, db/schema.rb, db/seeds.rb
=> Add admin-session

app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/customers/show.html.erb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb
=> Customer login,Signup

app/controllers/admin/genres_controller.rb, app/models/genre.rb, app/views/admin/genres/_form.html.erb, app/views/admin/genres/_index.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb
=> Add genre-settings

app/controllers/admin/items_controller.rb, app/helpers/admin/items_helper.rb, app/models/item.rb, app/views/admin/items/_form.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb
=> Add item-new,edit

app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/customers/confirm_withdraw.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/homes/top.html.erb, app/views/public/registrations/new.html.erb, config/locales/devise.ja.yml
・会員の退会機能追加
・フラッシュメッセージの表示
・エラーメッセージの日本語化追加
=> Add 会員退会機能、メッセージの日本語化、エラーメッセージ

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb
=> Add customer-list

app/controllers/admin/items_controller.rb, app/controllers/admin/sessions_controller.rb, app/views/admin/items/index.html.erb, app/views/admin/items/show.html.erb, app/views/layouts/_header.html.erb, config/routes.rb
・admin商品一覧表
・admin商品詳細
・/admin/top→/admin
=> Add admin/items/index,show

app/controllers/public/cart_items_controller.rb, app/controllers/public/orders_controller.rb, app/models/address.rb, app/views/public/cart_items/_index.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/orders/complete.html.erb, app/views/public/orders/confirm.html.erb, app/views/public/orders/new.html.erb, config/routes.rb
=> Cart items index

app/controllers/public/addresses_controller.rb, app/controllers/public/cart_items_controller.rb, app/views/public/cart_items/_index.html.erb
=> Add カート内商品数変更機能

app/controllers/application_controller.rb
=> Add admin-rights

config/application.rb
=> Add time-zone

app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/public/items/_index.html.erb, config/locales/ja.yml
* kaminiariにbootstrapを適用
* 文字表記を変更
=> ページネーションのデザインを修正

config/locales/ja.yml
=> Edit ja.yml

app/models/address.rb, app/models/customer.rb, app/models/item.rb
・郵便番号、電話番号　数字のみ入力可能
・会員登録フリガナを全角カタカナのみ適応
・商品金額１円以上
=> Add　validates

app/models/order.rb
=> 注文モデルバリデーション追加

app/controllers/public/orders_controller.rb
=> fix public-orders

app/controllers/public/orders_controller.rb, app/views/public/orders/new.html.erb
新しいお届け先の追加に失敗した時のフラッシュメッセージを追加
=> add flash message

app/assets/stylesheets/application.css, app/javascript/stylesheets/application.scss, app/views/layouts/_header.html.erb, app/views/public/homes/about.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/_genre_list.html.erb, app/views/public/items/_index.html.erb
・about　フォントサイズ変更
・top,header 文字位置調整
・ジャンル検索,商品名 文字色変更
=> top.about　レイアウト調整

app/views/admin/sessions/new.html.erb
=> 管理者ログアウトメッセージ

app/views/admin/genres/index.html.erb, app/views/admin/items/index.html.erb
=> Design settings

app/views/admin/customers/edit.html.erb, app/views/admin/items/_form.html.erb, app/views/admin/sessions/new.html.erb, app/views/public/orders/confirm.html.erb
=> テーブルタグを使用したフォームの修正

app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/genres/_edit_form.html.erb, app/views/admin/genres/_index.html.erb, app/views/admin/genres/_new_form.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/items/_form.html.erb, app/views/admin/orders/_order_detail.html.erb, app/views/admin/orders/_order_total_amount.html.erb, app/views/admin/orders/_show.html.erb, app/views/admin/orders/show.html.erb
・会員一覧、会員情報詳細、会員情報編集の画面修正
・注文履歴詳細の画面修正
・ジャンル一覧、ジャンル修正の画面修正
その他軽微な調整
=> Fix layout admin
